#!/usr/bin/env python3
"""Entry point for the privesc script"""

import argparse
import sys
from pathlib import Path

# Allow running from the project root
sys.path.insert(0, str(Path(__file__).parent))

from core.context import build_context
from core.reporter import Reporter
from core.runner import Runner


def parse_args():
    parser = argparse.ArgumentParser(
        description="Just Another Privesc Script",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "--quick", action="store_true",
        help="Skip slow modules (large filesystem searches)",
    )
    parser.add_argument(
        "--module", metavar="NAME",
        help="Run a single module by name",
    )
    parser.add_argument(
        "--tags", metavar="TAG[,TAG]",
        help="Only run modules with these tags (comma-separated)",
    )
    parser.add_argument(
        "--skip-tags", metavar="TAG[,TAG]",
        help="Skip modules with these tags",
    )
    parser.add_argument(
        "--output", metavar="DIR",
        default="/tmp",
        help="Directory to write JSON and text reports",
    )
    parser.add_argument(
        "--no-color", action="store_true",
        help="Disable colored output",
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List available modules and exit",
    )
    parser.add_argument(
        '--mode', 
        choices=['collect', 'analyse'], 
        default="collect",
        help="Operation mode: 'collect' to gather data from target, 'analyse' to process it on attacking machine."
    )
    parser.add_argument(
        '--raw-report',
        help="Raw json report generated by the 'collect' phase. Needed by 'analyse' phase"
    )
    return parser.parse_args()


def main():
    args = parse_args()

    if args.mode == "collect" and args.raw_report:
        print("--raw-report param is usable only with 'analyse' mode")
        exit()
    if args.mode == "analyse" and not args.raw_report:
        print("'analyse' mode require to specify an input report with the --raw-report param")
        exit()

    reporter = Reporter(
        output_dir=args.output,
        no_color=args.no_color,
    )
    runner = Runner(
        reporter=reporter,
        quick=args.quick,
        only_module=args.module,
        only_tags=args.tags.split(",") if args.tags else [],
        skip_tags=args.skip_tags.split(",") if args.skip_tags else [],
        mode=args.mode
    )

    if args.list:
        runner.list_modules()
        return

    ctx = build_context()
    runner.run(ctx, args.raw_report)


if __name__ == "__main__":
    main()
